### ISSUE TITLE
Type mismatch. Expected 'AbstractDriver'. Got 'Max7219'

### ISSUE THREAD

**Issue by lazyoldjack** [JWood48/toit-max7219#4]
Hi Jakob

I get this issue with your display driver example:

Type mismatch. Expected 'AbstractDriver'. Got 'Max7219' on line 48

I suspect it's something silly I'm doing, but I can't spot it. I **think** everything on my system is up to date but there are so many bits involved I don't know which bits would affect this. I'm a bit of a Toit noob, sorry.

**Comment by JWood48** [comment]
Hi 

I just updated the readme - you should be using version 1.1.0 for the Max7219 class to be compatible as a display driver.

to use the latest version use:

`toit pkg sync`

and then 

`toit pkg update`

**Comment by lazyoldjack** [comment]
Hi Jakob,

Brilliant, thanks, all working now.
